apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: http-server-cert
  namespace: default
spec:
  secretName: tls-secret  # The secret where the certificate and key will be stored
  issuerRef:
    name: letsencrypt-prod  # Reference to the ClusterIssuer created above
  commonName: example.com  # Your domain name
  dnsNames:
    - example.com  # Your domain name
