apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: simple-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
      - name: simple-python-app
        image: atatekeli/simple-python-app:v2 (initially used v1 to do troubleshooting and Dockerfile had app1.py for troubleshooting purposes, all were fixed to v2 and app.py repeatedly)
        ports:
        - containerPort: 8000