apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: simple-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
      - name: simple-python-app
        image: abhishekf5/crashlooptest:v2
        ports:
        - containerPort: 8000
        resources:
         limits:
          cpu: "25m"
          memory: "25Mi"